server:
  port: 8202
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysqlschema
   cloud:
     vault:
       token: 00000000-0000-0000-0000-000000000000
         scheme: http
           kv:
             enabled: true  
  jpa:
    hibernate:
      ddl-auto: update
    show:
      sql: true
