spring:
  application:
    name: patient-module
  datasource:
    url: jdbc:mysql://localhost:3306/mysqldb
    username: root
    password: MySql@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
  cloud:
    config:  
      uri: http://config-app

 